INSERT INTO ARTICLES	(ARTICLE_ID,TITLE,CATEGORY)	VALUES (1,'Titulo 1','Presente');
INSERT INTO ARTICLES	(ARTICLE_ID,TITLE,CATEGORY)	VALUES (2,'Titulo 2','Passado');
INSERT INTO ARTICLES	(ARTICLE_ID,TITLE,CATEGORY)	VALUES (3,'Titulo 3','Futuro');
INSERT INTO ARTICLES	(ARTICLE_ID,TITLE,CATEGORY)	VALUES (4,'Titulo 4','Indeterminado');
